### ISSUE TITLE
Merge subtopics file name misspell Generating training data

### ISSUE THREAD

**Issue by guspan-tanadi** [yueyu1030/AttrPrompt#3]
Hi, there.
The current file name for merge subtopics is as follow.
gen_train_data/merge_subtopics_mutl_label.py

Following the [Generating training data with attributed prompts (AttrPrompt)](https://github.com/yueyu1030/AttrPrompt/tree/main/gen_train_data#generating-training-data-with-attributed-prompts-attrprompt-1) provided command as
python merge_subtopics_multi_label.py

The command will likely execute without file intended.

Apart the issue such trivial matter file name have a bit misspell.

**Comment by yueyu1030** [comment]
Thanks for pointing this out! We appreciate it.
