### ISSUE TITLE
Request for Code to Measure Similarity and Frequency Between Sentences

### ISSUE THREAD

**Issue by kaizhuanren** [yueyu1030/AttrPrompt#7]
Dear yueyu1030,

First of all, thank you for your work on this project. I have been going through the codebase and the associated research paper, and I could not find the specific implementation for measuring the similarity and frequency between sentences. Additionally, the methodology for aggregating these similarities (e.g., using mean or maximum values) is not detailed in the paper.

I would greatly appreciate it if you could share the relevant code or provide more information on how the sentence similarities are calculated and aggregated. This will be very helpful for me to reproduce and compare my experimental results with yours.

Thank you in advance for your assistance.

**Comment by yueyu1030** [comment]
For calculating the sentence similarity, we use Sentence BERT. The link and the documentation is in [sentence-transformers/stsb-mpnet-base-v2](https://huggingface.co/sentence-transformers/all-mpnet-base-v2).
